//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Challange
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db4TuneEntities : DbContext
    {
        public db4TuneEntities()
            : base("name=db4TuneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbCommnet> TbCommnets { get; set; }
        public virtual DbSet<tbTopic> tbTopics { get; set; }
        public virtual DbSet<TbUser> TbUsers { get; set; }
    }
}
