//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Challange
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCommnet
    {
        public int Id { get; set; }
        public string nmComment { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DtComment { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
