//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Challange
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTopic
    {
        public int Id { get; set; }
        public string nmTopic { get; set; }
        public Nullable<int> idUserCreator { get; set; }
        public Nullable<System.DateTime> DtCreator { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
