//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Challange
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUser
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DtNascimento { get; set; }
        public string user { get; set; }
        public string senha { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
